name: Snake Game

on:
  schedule:
    - cron: '0 */12 * * *'  # Executa a cada 12 horas
  workflow_dispatch:  # Permite execução manual
  push:
    branches:
      - main  # Executa em cada push para a branch main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar animação da cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
